<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-09T17:34:17 IST" name="Default suite" finished-at="2025-07-09T17:34:38 IST" duration-ms="21285">
    <groups>
    </groups>
    <test started-at="2025-07-09T17:34:17 IST" name="Default test" finished-at="2025-07-09T17:34:38 IST" duration-ms="21285">
      <class name="organizations.TC_VT_010_Test">
        <test-method is-config="true" signature="reportconfig()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:17 IST" name="reportconfig" finished-at="2025-07-09T17:34:17 IST" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportconfig -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:17 IST" name="openBrowser" finished-at="2025-07-09T17:34:20 IST" duration-ms="3328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:20 IST" name="login" finished-at="2025-07-09T17:34:26 IST" duration-ms="5358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="clickOnOrganizations()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:26 IST" name="clickOnOrganizations" finished-at="2025-07-09T17:34:34 IST" duration-ms="8582" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Organizations page is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Organizations page is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at organizations.TC_VT_010_Test.clickOnOrganizations(TC_VT_010_Test.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnOrganizations -->
        <test-method is-config="true" signature="logout()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:35 IST" name="logout" finished-at="2025-07-09T17:34:38 IST" duration-ms="2850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:38 IST" name="closeBrowser" finished-at="2025-07-09T17:34:38 IST" duration-ms="768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="reportBackup()[pri:0, instance:organizations.TC_VT_010_Test@587e5365]" started-at="2025-07-09T17:34:38 IST" name="reportBackup" finished-at="2025-07-09T17:34:39 IST" duration-ms="888" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportBackup -->
      </class> <!-- organizations.TC_VT_010_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
